#!/bin/sh
# Copyright (c) 2026 Rodrigo Monteiro Junior. All Rights Reserved.

# 'Test/Parse' - Test file for the 'parse' argument parsing function

DIR=$(dirname "$0")

# shellcheck source=./common
. "$DIR"/../common

testParse() {
  parse -var testVar - "test value"
  assertEquals "test value" "${testVar?}"

  parse -var tv1 -var tv2 "tv 1" "tv 2"
  assertEquals "tv 1" "${tv1?}"
  assertEquals "tv 2" "${tv2?}"

  parse -var foo "foo" "bar"
  assertEquals "foo" "${foo?}"
}

# shellcheck source=./shunit2/shunit2
. "$DIR"/../shunit2/shunit2
