#!/bin/sh
# Copyright (c) 2026 Rodrigo Monteiro Junior. All Rights Reserved.

# 'New Script' - Shell scripting creation tool

DIR=$(dirname "$0")

# shellcheck source=./common
. "$DIR"/common

prompt_edit() {
  file="$1"
  printf "Program exists! Edit? (N/y): "
  read -r option
  if echo "$option" | grep -qi 'y'; then
    exec "$DIR"/es "$file"
  else
    die "Leaving file as is."
  fi
}

parse -var srcName - "$@"

program="$(with_bin "${srcName?}")"

exists "$program" && prompt_edit "${srcName?}"

touch "$program"
chmod +x "$program"
header >"$program"

nvim "$program"
